# Generated by Django 4.1.13 on 2024-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizentree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.IntegerField(),
        ),
    ]
