# Generated by Django 4.1.13 on 2024-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizentree', '0002_alter_item_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='kaizentree.tag'),
        ),
    ]
