# Generated by Django 4.1.13 on 2024-02-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kaizentree', '0004_category_alter_item_name_alter_item_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kaizentree.category'),
        ),
    ]
