# Generated by Django 4.1.13 on 2024-02-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizentree', '0005_alter_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
