# Generated by Django 4.1.13 on 2024-02-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaizentree', '0006_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
